version: 2
sources:
- name: tpch
  database: SNOWFLAKE_SAMPLE_DATA
  schema: TPCH_SF1
  tables:
  - name: orders
    identifier: ORDERS 
    meta:
      mappings:
        eventTimestamp: o_orderdate
        userId: o_custkey
      aggregates: 
        total_orders_priority:
          measures: ['count_of_rows', 'unique_orders']
          dimensions: ['o_orderdate', 'o_shippriority', 'o_orderpriority']
      measures: 
        count_of_rows:
          aggregation: count
        unique_orders:
          dimension: o_orderkey
          aggregation: approximate_unique
      dimensions:
        o_orderkey: {column : o_orderkey}
        o_custkey: {column : o_custkey}
        o_orderdate: {column: o_orderdate}
        o_orderstatus: {column: o_orderstatus}
        o_clerk: {column: o_clerk}
        o_shippriority: {column: o_shippriority}
        o_orderpriority: {column: o_orderpriority}
        custom_sql: {sql: "CONCAT('1', {{TABLE}}.o_orderstatus)" }
        
    columns:
    - name: o_orderkey
      description: 'The unique identifier of order'
      meta:
        type: double